// =============================================================================
// lib/config/types.ts — the shape of a config file: every setting this CDK app reads.
//
// You do not edit this file to configure an install. Copy config/example.ts to
// config/<your-env>.ts, edit that, and deploy with:
//
//   npx cdk deploy --all -c config=<your-env>
//
// Every field has a comment; your editor shows it when you hover over a field in config/<env>.ts.
//
// The toggle model: every component has `enabled: true | false`. When a
// component is off but something else still needs it (for example the LangSmith
// IAM role needs a database), you give the ID of the one you already have in an
// `existing...` field. validateConfig (validate.ts) tells you when one is missing.
// =============================================================================
import type { Sizes } from './sizing';

/** How protected an install is: Multi-AZ, deletion protection, backups, cache failover (README.md, Sizing). */
export type Environment = 'dev' | 'stage' | 'prod';
/**
 * How big an install is: machines, database classes, storage, SmithDB tier (README.md, Sizing).
 * 'lab' is the cheapest shape that runs everything, for functional tests only (environment 'dev').
 */
export type Size = 'lab' | 'small' | 'medium' | 'large';

/**
 * How pods get AWS credentials.
 * - 'irsa': IAM Roles for Service Accounts. The role trusts the cluster's OIDC issuer;
 *           the ServiceAccount carries an `eks.amazonaws.com/role-arn` annotation.
 * - 'podIdentity': EKS Pod Identity. The role trusts pods.eks.amazonaws.com; an EKS
 *           "pod identity association" maps namespace/ServiceAccount -> role.
 * Same roles and permissions either way; only the trust policy and the binding differ.
 */
export type WorkloadIdentity = 'irsa' | 'podIdentity';

/**
 * How HTTPS traffic reaches LangSmith (README.md, Network).
 * - 'envoy-gateway': CDK creates the internal ALB, its HTTPS listener and a target group. post-deploy/04
 *           installs Envoy Gateway and binds its proxy pods to that target group. LangSmith and every agent
 *           deployment get Gateway API HTTPRoutes. Upstream Terraform's default.
 * - 'alb':  the AWS Load Balancer Controller creates the ALB from the LangSmith chart's Ingress during
 *           `helm install`, and the ALB sends traffic straight to the pods. No extra proxy.
 */
export type IngressMode = 'envoy-gateway' | 'alb';
export const DEFAULT_INGRESS_MODE: IngressMode = 'envoy-gateway';

/** The address plan of a new VPC with pods in the private subnets, layout 'A' (NetworkConfig.addressPlan). */
export type AddressPlan = 'standard' | 'large';

/**
 * The network layout of a new VPC (NetworkConfig.layout, README.md, Network):
 * - 'B' (default, recommended), a separate pod range: only nodes, the ALB, the databases and endpoints use routable addresses; pods get
 *        IPs from a 100.64.0.0/16 secondary CIDR. The VPC CNI finds the pod subnets by their
 *        kubernetes.io/role/cni tag (enhanced subnet discovery): no ENIConfig, one deploy.
 * - 'A', pods in the private subnets: everything, pods included, in routable subnets. LangChain's Terraform module works this way.
 */
export type Layout = 'A' | 'B';
export const DEFAULT_LAYOUT: Layout = 'B';
/** The pod range of a new VPC with a separate pod range, layout 'B' (NetworkConfig.podCidr). */
export const DEFAULT_POD_CIDR = '100.64.0.0/16';

/**
 * The VPC CNI add-on version pinned when pods use their own subnets and eks.addonVersions.vpcCni
 * is not set. Excluding the node subnets from pod IPs (tag kubernetes.io/role/cni=0) needs
 * VPC_CNI_MIN_FOR_SUBNET_TAGS or later; the EKS default version for a Kubernetes release may be older.
 */
export const VPC_CNI_SUBNET_TAGS_VERSION = 'v1.23.1-eksbuild.1';
export const VPC_CNI_MIN_FOR_SUBNET_TAGS = '1.22.2';

/** A subnet you already have. Both values are on the subnet's page in the VPC console. */
export interface SubnetRef {
  /** Subnet ID, e.g. subnet-0123456789abcdef0 */
  id: string;
  /** Availability Zone name, e.g. us-east-1a */
  az: string;
}

export interface NetworkConfig {
  /**
   * true  = create a new VPC in a separate stack `<name>-network` (lib/stacks/network-stack.ts).
   * false = use your VPC: fill in vpcId, vpcCidrs and privateSubnets (README.md, Network).
   */
  createVpc: boolean;

  // ---- only when createVpc = true ------------------------------------------------
  /** Exactly 3 AZ names. Avoid AZ IDs EKS does not support (use1-az3, usw1-az2, cac1-az3). */
  availabilityZones?: string[];
  /**
   * 'B' (default, recommended) = a separate pod range: pods in a 100.64.0.0/16 secondary CIDR, so few routable IPs are used.
   * 'A' = pods in the private subnets: everything in routable subnets. Set it explicitly: changing it replaces the VPC.
   */
  layout?: Layout;
  /** 'single' = one NAT gateway (cheaper). 'per-az' = one per AZ (survives an AZ outage). Default: single for dev, per-az otherwise. */
  natMode?: 'single' | 'per-az';
  /**
   * layout 'A' only: the size of the address plan (README.md, Network).
   * 'standard' = 10.0.0.0/21, a /23 private subnet per AZ (about 500 IPs each).
   * 'large'    = 10.0.0.0/20, a /22 private subnet per AZ (about 1,000 IPs each).
   * Default: 'large' for environment 'prod', 'standard' otherwise. Set it explicitly: changing it
   * later replaces the VPC and everything in it, so a later `environment` change must not change it.
   */
  addressPlan?: AddressPlan;
  /**
   * layout 'B' only: the VPC's second range, for pod addresses. A /16 inside 100.64.0.0/10 or
   * 198.19.0.0/16 that nothing your pods must reach uses (README.md, Network). Each AZ gets a /19
   * of it. Default '100.64.0.0/16'. Set it explicitly: changing it replaces the pod subnets.
   */
  podCidr?: string;

  // ---- only when createVpc = false -----------------------------------------------
  /** Your VPC ID, e.g. vpc-0123456789abcdef0 */
  vpcId?: string;
  /** Every CIDR of the VPC, including a secondary pod CIDR. Security group rules are built from these. */
  vpcCidrs?: string[];
  /** Private subnets, one per AZ, at least 2 AZs: nodes, RDS, Valkey, ALB and the EKS control plane ENIs. */
  privateSubnets?: SubnetRef[];
  /**
   * A separate pod range on your VPC: pod subnets from a secondary CIDR, one per AZ (same AZs as privateSubnets).
   * Tag each one kubernetes.io/role/cni=1, and each private subnet kubernetes.io/role/cni=0
   * (README.md, Network); post-deploy/04 step 3 checks the tags. Empty = pods use the private subnets.
   */
  podSubnets?: SubnetRef[];
  /** Your S3 gateway endpoint ID (vpce-...). If set, this install's roles may use its buckets only through it. */
  s3GatewayEndpointId?: string;
}

export interface EksConfig {
  /** false = do not create a cluster; give existingClusterName (and existingOidcIssuer for IRSA). */
  enabled: boolean;
  /** Kubernetes version, e.g. '1.34'. */
  version: string;
  /**
   * CIDRs allowed to reach the EKS API over the internet. [] = private endpoint only
   * (kubectl/helm must then run inside the VPC, e.g. from the bastion).
   * Dev from a laptop: your egress IP, e.g. ['203.0.113.10/32']. Set back to [] and redeploy to go private-only.
   */
  publicAccessCidrs: string[];
  /** IAM role ARNs that become cluster admins (EKS access entries). The bastion role is added automatically. */
  adminRoleArns: string[];
  /** Only when enabled = false: the name of your existing cluster. */
  existingClusterName?: string;
  /** Only when enabled = false and workloadIdentity = 'irsa': the issuer host, e.g. oidc.eks.us-east-1.amazonaws.com/id/EXAMPLE. Its IAM OIDC provider must already exist. */
  existingOidcIssuer?: string;
  /**
   * Days to keep the control-plane logs in the CloudWatch log group /aws/eks/<name>/cluster,
   * which this app creates (tagged, deleted with the stack). Must be a CloudWatch retention value. Default 90.
   */
  logRetentionDays?: number;
  /** The managed node group general-<instance type>. Its size comes from `size` (sizes.node*). */
  nodeGroup: { enabled: boolean };
  /** EKS managed add-ons. Each one is a native AWS::EKS::Addon resource. */
  addons: {
    vpcCni: boolean;
    kubeProxy: boolean;
    coreDns: boolean;
    ebsCsiDriver: boolean;
    metricsServer: boolean;
    /** Required when workloadIdentity = 'podIdentity'. Ignored for 'irsa'. */
    podIdentityAgent: boolean;
  };
  /** Optional add-on versions, e.g. { coreDns: 'v1.12.1-eksbuild.2' }. Empty = the EKS default for the Kubernetes version. */
  addonVersions?: Partial<Record<'vpcCni' | 'kubeProxy' | 'coreDns' | 'ebsCsiDriver' | 'metricsServer' | 'podIdentityAgent', string>>;
}

/** A PostgreSQL instance you already have (only when that instance's enabled = false). */
export interface ExistingPostgres {
  /** Endpoint host name, e.g. mydb.abcdefg.us-east-1.rds.amazonaws.com */
  endpoint: string;
  /** The DbiResourceId (db-ABC...) — used in rds-db:connect permissions. */
  resourceId: string;
  /** ARN of the Secrets Manager secret holding the master credentials (read by the DB bootstrap Job). */
  masterSecretArn: string;
}

export interface PostgresInstanceConfig {
  enabled: boolean;
  /** Engine version. A major version alone ('16') lets RDS pick its default minor version. */
  engineVersion: string;
  existing?: ExistingPostgres;
}

export interface LangSmithConfig {
  /** Prefix of every resource name (cluster, roles, buckets, secrets). Lowercase letters, digits, '-'; max 20 characters. */
  name: string;
  /** The 12-digit AWS account ID to deploy into. */
  account: string;
  /** AWS region, e.g. us-east-1. */
  region: string;
  /**
   * The qualifier of this environment's own CDK bootstrap toolkit (lowercase letters and digits, max 10):
   *   npx cdk bootstrap ... --qualifier <q> --toolkit-stack-name CDKToolkit-<q>
   * Recommended: one toolkit per environment. Its execution policies are scoped to this `name`
   * (README.md, Step 2), so two environments sharing the account's default toolkit would replace each
   * other's policies. Leave it out to use the default toolkit (CDKToolkit).
   */
  cdkQualifier?: string;
  /** dev | stage | prod — how protected: Multi-AZ, deletion protection, backups, cache failover. Also the default `size`. */
  environment: Environment;
  /** lab | small | medium | large — how big. Default: dev → small, stage → medium, prod → large. 'lab' needs environment 'dev'. */
  size?: Size;
  /** Optional overrides of single values, e.g. { nodeMax: 8 }. Check the result with `npm run sizes`. */
  sizes?: Partial<Sizes>;
  /** How pods get AWS credentials. Default and recommended for this repo: 'irsa'. */
  workloadIdentity: WorkloadIdentity;
  /** Optional: the ARN of a permissions boundary policy put on every IAM role this app creates. */
  permissionsBoundaryArn?: string;
  /**
   * What `cdk destroy` does with data: 'retain' keeps buckets, secrets, the KMS key and takes
   * final DB snapshots; 'destroy' deletes them (test environments only; non-empty buckets still need emptying first).
   */
  dataRemovalPolicy: 'retain' | 'destroy';
  /**
   * Optional extra tags on every resource and on both stacks, next to the two this app always sets
   * (app=langsmith, langsmith-env=<name>). E.g. { 'cost-center': '1234', owner: 'platform-team' }.
   */
  extraTags?: Record<string, string>;

  network: NetworkConfig;

  /** How users reach LangSmith: the internal ALB at https://<hostname> (README.md, Network). */
  ingress?: {
    /** Default 'envoy-gateway' (see IngressMode). */
    mode?: IngressMode;
    /** Who may reach https://<hostname> through the internal ALB (port 443). Empty or left out = the VPC CIDRs. */
    allowedCidrs?: string[];
  };

  /** KMS key for EKS Kubernetes-Secrets envelope encryption. Everything else uses AWS-managed keys. */
  kms: {
    enabled: boolean;
    /** Only when enabled = false: your key's ARN. Leave both off/empty for no secrets encryption. */
    existingKeyArn?: string;
  };

  eks: EksConfig;

  s3: {
    /** <name>-blob-<account>: large trace payloads and attachments. */
    blob: { enabled: boolean; existingBucketName?: string };
    /** <name>-smithdb-<account>: SmithDB's durable trace data. */
    smithdb: { enabled: boolean; existingBucketName?: string };
  };

  /** Secrets Manager entries under <name>/ (README.md, Appendix D). */
  secrets: {
    enabled: boolean;
    /** Email of the first organisation admin. */
    adminEmail: string;
  };

  postgres: {
    /** <name>-core: LangSmith + Fleet/Insights/Chat databases (PostgreSQL 16). */
    core: PostgresInstanceConfig;
    /** <name>-metastore: the SmithDB catalog (PostgreSQL 18). */
    metastore: PostgresInstanceConfig;
  };

  /** ElastiCache Valkey with IAM authentication (users <name>-core, -fleet, -insights, -polly). */
  valkey: {
    enabled: boolean;
    /** e.g. '8.1'. Check what your region offers: aws elasticache describe-cache-engine-versions --engine valkey */
    engineVersion: string;
    /** Only when enabled = false: your cache. It must have the four IAM users named as above. */
    existing?: { primaryEndpoint: string; replicationGroupId: string };
  };

  /** IAM roles for the workloads (README.md, Appendix C). Each can be switched off. */
  workloadRoles: {
    langsmith: boolean;
    smithdb: boolean;
    externalSecrets: boolean;
    loadBalancerController: boolean;
    clusterAutoscaler: boolean;
    /** Add Amazon Bedrock InvokeModel permissions to the LangSmith role. */
    bedrock: boolean;
  };

  /** Where LangSmith runs in Kubernetes. */
  kubernetes: {
    /** Namespace of the LangSmith Helm release. */
    langsmithNamespace: string;
    /**
     * Pod Identity only: the LangSmith ServiceAccounts that get the shared <name>-langsmith role
     * (one pod identity association each). IRSA ignores this list: its trust covers every
     * ServiceAccount in the namespace. Names assume the Helm release is called "langsmith".
     */
    langsmithServiceAccounts: string[];
  };

  dns: {
    /** What users type in the browser; must be inside privateZone.domain. */
    hostname: string;
    privateZone: {
      enabled: boolean;
      /** e.g. example.internal */
      domain: string;
      /** Only when enabled = false: your private hosted zone ID. */
      existingZoneId?: string;
    };
    /**
     * An ISSUED ACM certificate for the hostname, in this account and region.
     * ingress.mode 'envoy-gateway' (default): required, because CDK creates the HTTPS listener — import
     * PEM files with post-deploy/00 BEFORE `cdk deploy`. ingress.mode 'alb': may be empty and imported later.
     */
    certificateArn?: string;
  };

  /** SSM-only jump host in a private subnet (no SSH, no inbound rule, no public IP). */
  bastion: {
    enabled: boolean;
    instanceType: string;
    /** Create ssm/ssmmessages/ec2messages interface endpoints (only needed when the VPC has no NAT and none exist). */
    createSsmEndpoints: boolean;
    /** Optional: a managed policy to attach to the bastion role, e.g. one created from iam/operator-policy.json. */
    operatorPolicyArn?: string;
  };

  /**
   * Bring your own IAM roles. For each role you set here, CDK creates NOTHING for it and
   * never changes it — it only passes the ARN where the role is used. Print what each role
   * must contain with: npm run iam-pack -- -c config=<env>
   */
  existingRoles: ExistingRoles;
  /**
   * Must be true when you bring your own IRSA roles (workloadIdentity = 'irsa'): their trust
   * policy names the cluster's OIDC issuer, which exists only after the first deploy, so your
   * IAM team updates the trust after the cluster is created (README.md, Appendix C).
   */
  irsaTrustManagedExternally?: boolean;
}

/** One optional ARN per role. Keys match the role names: <name>-eks-cluster, <name>-eks-node, ... */
export interface ExistingRoles {
  eksCluster?: string;
  eksNode?: string;
  bastion?: string;
  /** Needed together with `bastion`: the name of the instance profile that contains that role. */
  bastionInstanceProfileName?: string;
  vpcCni?: string;
  ebsCsi?: string;
  langsmith?: string;
  smithdb?: string;
  externalSecrets?: string;
  loadBalancerController?: string;
  clusterAutoscaler?: string;
}

// -----------------------------------------------------------------------------
// Defaults that are applied where a value is read (the config file may leave them out).
// -----------------------------------------------------------------------------
/** The ingress mode, with the default applied. */
export function ingressMode(cfg: LangSmithConfig): IngressMode {
  return cfg.ingress?.mode ?? DEFAULT_INGRESS_MODE;
}

/** The layout of a new VPC, with the default applied ('B'). */
export function layoutOf(cfg: LangSmithConfig): Layout {
  return cfg.network.layout ?? DEFAULT_LAYOUT;
}

/** The pod range of a new VPC with a separate pod range, with the default applied. */
export function podCidrOf(cfg: LangSmithConfig): string {
  return cfg.network.podCidr ?? DEFAULT_POD_CIDR;
}

/** The address plan of a new VPC, with the default applied (prod 'large', otherwise 'standard'). */
export function addressPlan(cfg: LangSmithConfig): AddressPlan {
  return cfg.network.addressPlan ?? (cfg.environment === 'prod' ? 'large' : 'standard');
}
