// =============================================================================
// 9 — Secrets Manager
// WHAT  Every application secret under <name>/ (README.md, Appendix D):
//         license-key, fernet/agent-builder, fernet/insights, fernet/polly
//             -> created with the placeholder REPLACE_ME; post-deploy/01 writes the real value
//         initial-org-admin-password, api-key-salt, jwt-secret
//             -> random values generated by Secrets Manager itself
//         initial-org-admin-email -> from config
//         connections -> host names and IAM user names (no passwords), for the ExternalSecrets
// WHY   External Secrets Operator copies these into Kubernetes Secrets, so nothing secret
//       lives in Helm values, in this repo, or in the CloudFormation template.
//       api-key-salt, jwt-secret and the Fernet keys must NEVER change after first use (API keys
//       and encrypted data become unreadable): the secrets are retained on delete by default and
//       CloudFormation never regenerates a value it already generated.
// HOW   AWS::SecretsManager::Secret. The license and Fernet keys are not generated here because
//       Secrets Manager cannot produce a Fernet key (url-safe base64 of exactly 32 bytes), and a
//       license must never be put in a template. "unsafePlainText" below only ever carries the
//       placeholder, the admin email and host names — never a secret.
// =============================================================================
import { aws_secretsmanager as sm, RemovalPolicy, SecretValue, Stack } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { LangSmithConfig } from '../config';
import { CORE_DB_USERS, METASTORE_DB_USER, Names } from '../naming';
import { PostgresInfo } from './postgres';
import { ValkeyInfo } from './valkey';

/** Secrets that post-deploy/01-seed-secrets.sh fills in (only while they still hold this value). */
export const PLACEHOLDER = 'REPLACE_ME';
export const SEEDED_SECRETS = ['license-key', 'fernet/agent-builder', 'fernet/insights', 'fernet/polly'] as const;

export interface AppSecretsProps {
  cfg: LangSmithConfig;
  names: Names;
  removalPolicy: RemovalPolicy;
  core?: PostgresInfo;
  metastore?: PostgresInfo;
  valkey?: ValkeyInfo;
}

export class AppSecrets extends Construct {
  constructor(scope: Construct, id: string, props: AppSecretsProps) {
    super(scope, id);
    const { cfg, names } = props;
    const secret = (logicalId: string, suffix: string, description: string, value: Partial<sm.SecretProps>) => {
      const s = new sm.Secret(this, logicalId, { secretName: names.secret(suffix), description, ...value });
      s.applyRemovalPolicy(props.removalPolicy);
      return s;
    };

    // ---- filled in later by post-deploy/01-seed-secrets.sh ------------------------
    const placeholder = { secretStringValue: SecretValue.unsafePlainText(PLACEHOLDER) };
    secret('LicenseKey', 'license-key', 'LangSmith license key (set by post-deploy/01)', placeholder);
    secret('FernetAgentBuilder', 'fernet/agent-builder', 'Fleet encryption key - never change (set by post-deploy/01)', placeholder);
    secret('FernetInsights', 'fernet/insights', 'Insights encryption key - never change (set by post-deploy/01)', placeholder);
    secret('FernetPolly', 'fernet/polly', 'Chat (Polly) encryption key - never change (set by post-deploy/01)', placeholder);

    // ---- generated by Secrets Manager ------------------------------------------------
    secret('AdminPassword', 'initial-org-admin-password', 'LangSmith initial org admin password', {
      generateSecretString: { passwordLength: 32, requireEachIncludedType: true, excludeCharacters: '"\'\\/@`$ ' },
    });
    secret('ApiKeySalt', 'api-key-salt', 'LangSmith API key salt - never change', {
      generateSecretString: { passwordLength: 44, excludePunctuation: true },
    });
    secret('JwtSecret', 'jwt-secret', 'LangSmith JWT secret - never change', {
      generateSecretString: { passwordLength: 44, excludePunctuation: true },
    });

    // ---- from config -------------------------------------------------------------------
    secret('AdminEmail', 'initial-org-admin-email', 'LangSmith initial org admin email', {
      secretStringValue: SecretValue.unsafePlainText(cfg.secrets.adminEmail),
    });

    // ---- connection strings: hosts and IAM user names only ---------------------------
    // Redis database index: 0 core, 1 Fleet, 2 Chat, 3 Insights (post-deploy/04 maps these keys).
    if (props.core && props.metastore && props.valkey) {
      const core = props.core.endpoint;
      const redis = props.valkey.primaryEndpoint;
      const user = (consumer: string) => names.cacheUser(consumer);
      // Each database is named after its login role (k8s/db-bootstrap/core.sql), except LangSmith's own.
      const [app, fleet, insights, polly] = CORE_DB_USERS;
      const pg = (role: string, db: string) => `postgresql://${role}@${core}:5432/${db}?sslmode=require`;
      const connections = {
        core_host: core,
        // The LangSmith chart's postgres.external connection URL has no scheme; the add-ons' URLs do.
        core_postgres_url: `${app}@${core}:5432/langsmith?sslmode=require`,
        core_redis_url: `rediss://${user('core')}@${redis}:6379/0`,
        metastore_host: props.metastore.endpoint,
        metastore_db: 'smithdb',
        metastore_user: METASTORE_DB_USER,
        fleet_postgres_url: pg(fleet, fleet),
        fleet_redis_url: `rediss://${user('fleet')}@${redis}:6379/1`,
        polly_postgres_url: pg(polly, polly),
        polly_redis_url: `rediss://${user('polly')}@${redis}:6379/2`,
        insights_postgres_url: pg(insights, insights),
        insights_redis_url: `rediss://${user('insights')}@${redis}:6379/3`,
      };
      secret('Connections', 'connections', 'LangSmith connection strings (IAM auth, no passwords)', {
        secretStringValue: SecretValue.unsafePlainText(Stack.of(this).toJsonString(connections)),
      });
    }
  }
}
