#!/usr/bin/env bash
# =============================================================================
# post-deploy/01-seed-secrets.sh — put the license key and the 3 Fernet keys into
# Secrets Manager
#
#   ./post-deploy/01-seed-secrets.sh
#
# WHAT   Fills four secrets that CDK created with the placeholder value REPLACE_ME:
#          <prefix>license-key            from LICENSE_KEY_FILE (post-deploy/settings.env)
#          <prefix>fernet/agent-builder   Fleet encryption key        (generated here)
#          <prefix>fernet/insights        Insights encryption key     (generated here)
#          <prefix>fernet/polly           Chat (Polly) encryption key (generated here)
# WHY    CDK cannot do this itself: a license must never be put in a CloudFormation
#        template, and Secrets Manager cannot generate a Fernet key (url-safe base64 of
#        exactly 32 random bytes). The other secrets (admin password, API key salt, JWT
#        secret, admin email, connections) are already complete.
#        The Fernet keys must NEVER change once LangSmith has used them (encrypted data
#        becomes unreadable), so a secret is written ONLY while it still holds exactly
#        REPLACE_ME. Anything else is kept. Re-running this script is always safe.
# HOW    For each secret: read the current value into a private temp file, compare it
#        with REPLACE_ME, and if it matches write the new value with
#        `aws secretsmanager put-secret-value --secret-string file://<temp file>`.
#        Values are never put on the command line and never printed.
# VERIFY aws secretsmanager list-secrets --filters Key=name,Values=<prefix> --query 'SecretList[].Name'
#        and re-run this script: every line should say "kept".
# NEEDS  aws, jq, openssl; AWS credentials for the account (secretsmanager:GetSecretValue
#        and secretsmanager:PutSecretValue on <prefix>*).
# =============================================================================
set -euo pipefail
umask 077
cd "$(dirname "$0")/.."
# shellcheck source-path=SCRIPTDIR/..
. post-deploy/lib.sh

need_tools aws jq openssl
SECRETS_PREFIX=$(out SecretsPrefix)

# put_value <secret id> <file> <label>: write the file's content as the secret's new value.
put_value() {
  aws secretsmanager put-secret-value --secret-id "$1" --secret-string "file://$2" >/dev/null
  rm -f "$2"
  log "$1: set ($3)"
}

# gen_fernet: a Fernet key = url-safe base64 of 32 random bytes (44 characters, no newline).
gen_fernet() { openssl rand -base64 32 | tr '+/' '-_' | tr -d '\n'; }

section "01 Seed the license key and the Fernet keys"

# ---------------------------------------------------------------- license ----
# WHAT  <prefix>license-key from LICENSE_KEY_FILE.
# WHY   LangSmith refuses to start without it.
# HOW   CR/LF are stripped (a key copied on Windows or with a trailing newline still works).
id="${SECRETS_PREFIX}license-key"
if secret_is_placeholder "$id"; then
  [ -r "$LICENSE_KEY_FILE" ] || die "LICENSE_KEY_FILE '$LICENSE_KEY_FILE' is not readable (set it in post-deploy/settings.env)"
  tr -d '\r\n' < "$LICENSE_KEY_FILE" > "$TMP/license"
  [ -s "$TMP/license" ] || die "LICENSE_KEY_FILE '$LICENSE_KEY_FILE' is empty"
  put_value "$id" "$TMP/license" "from $LICENSE_KEY_FILE"
else
  log "$id: kept (already set; to replace a license later see README.md, Rotation)"
fi

# ---------------------------------------------------------------- Fernet ----
# WHAT  One Fernet key per add-on: Fleet (agent-builder), Insights, Chat (polly).
# WHY   Each add-on encrypts its stored credentials with its key. NEVER change one after
#       first use; back them up together with the databases.
for f in agent-builder insights polly; do
  id="${SECRETS_PREFIX}fernet/$f"
  if secret_is_placeholder "$id"; then
    gen_fernet > "$TMP/fernet"
    [ "$(wc -c < "$TMP/fernet" | tr -d ' ')" = 44 ] || die "generated Fernet key has the wrong length (openssl problem?)"
    put_value "$id" "$TMP/fernet" "new random Fernet key"
  else
    log "$id: kept (already set; never overwritten)"
  fi
done

log "done. The admin password was generated by Secrets Manager; read it with:"
log "  aws secretsmanager get-secret-value --secret-id ${SECRETS_PREFIX}initial-org-admin-password --query SecretString --output text"
log "You can now delete $LICENSE_KEY_FILE from this machine."
